environment:
  matrix:
  - configuration: Release
#  - configuration: Debug

install:
  - ps: Install-Product node 6

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\osrm

platform: x64

build_script:
  - CALL appveyor-build.bat

before_test:
  - node --version
  - npm --version
  - npm install --ignore-scripts
  - npm link --ignore-scripts
  - SET PATH=%CD%\osrm-deps\libs\bin;%PATH%
  - SET OSRM_BUILD_DIR=build\%Configuration%
  - npm test

artifacts:
  - path: osrm_Release.zip
    name: osrm_Release.zip
#  - path: osrm_Debug.zip
#    name: osrm_Debug.zip

branches:
  only:
    - master

deploy:
  provider: FTP
  server:
    secure: ef7oiQTTXFGt8NdNiOHm/uRFVrUttzyFbIlnaeHhQvw=
  username:
    secure: Bw+Se2GTJxA6+GtRkEc//tQSBHOuFIuJHBjFwR9cD+8=
  password:
    secure: eqwESZqxMXC/j5mOCpaXuw==
  folder: /
  enable_ssl: true
  active_mode: false
