language: cpp

sudo: false

matrix:
  include:
    - os: osx
      env: MASON_PLATFORM=osx
      compiler: clang
    - os: linux
      env: MASON_PLATFORM=linux
      compiler: clang
      addons:
        apt:
          packages: [ 'yasm' ]
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
      addons:
        apt:
          packages: [ 'yasm' ]
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64

before_install:
- if [[ "${MASON_PLATFORM}" == "osx" ]]; then brew install yasm ; fi

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
